name: Run Django on GitHub Actions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Create SQLite Database
      run: |
        touch db.sqlite3  # Ensure database file exists

    - name: Run Migrations
      run: |
        source venv/bin/activate
        python manage.py migrate --noinput
